[tox]
envlist = e2e
skipsdist = true
requires = tox>=4

[testenv:e2e]
basepython = python3
commands =
    python tests/tests_e2e.py
passenv = PIPEX_DEBUG, PIPEX_LOG_LEVEL
# To debug: PIPEX_DEBUG=1 tox -e e2e

[testenv:clean_e2e]
basepython = python3
commands =
    python -c "import shutil; shutil.rmtree('tests/e2e', ignore_errors=True)"
